name: Temporary Tests

on:
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Version override (should be set if no tag is set)'
        default: ''
      is_draft:
        description: 'Is this release draft?'
        default: 'false'
      is_prerelease:
        description: 'Is this prerelease?'
        default: 'false'
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    needs: publish
    permissions: write-all
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Extract version from package.json
        uses: amochkin/gha-json-value@v1-rc6
        id: extract-version
        with:
          property: version
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version_override != '' && github.event.inputs.version_override || github.steps.extract-version.outputs.value || github.ref }}
          release_name: v${{ github.event.inputs.version_override != '' && github.event.inputs.version_override || github.steps.extract-version.outputs.value || github.ref }}
          draft: ${{ github.event.inputs.is_draft }}
          prerelease: ${{ github.event.inputs.is_prerelease }}